In [74]:
import numpy as np
import math
A = np.matrix([[3,2,4],[1,1,2],[4,3,2]])


print("original: \n",A,"\n\n")
det = np.linalg.det
      
if det == 0:
    print("Det=0, ERRO")
else:
      
    m21 = A[2-1,1-1]/A[1-1,1-1]
    m31 = A[3-1,1-1]/A[1-1,1-1]
    m32 = A[3-1,2-1]/A[2-1,2-1]
      
M = np.matrix([[1,0,0],[-m21,1,0],[-m31,0,1]])
print(M, "\n\n")
N = M*A
print("primeiro prod: \n",N,"\n\n")     

if det == 0:
    print("Det=0, ERRO")
else:
   
    m32 = N[3-1,2-1]/N[2-1,2-1]
      
G = np.matrix([[1,0,0],[0,1,0],[0,-m32,1]])
print(G,"\n\n")

print("segundo prod: \n",(N*G),"\n\n")

b = np.array([1,2,3],dtype = "float")

b1 = np.dot(M,b)
b1 = np.squeeze(np.asarray(b1))
b2 = np.matmul(G,b1)
print(b2)

original: 
 [[3 2 4]
 [1 1 2]
 [4 3 2]] 


[[ 1.          0.          0.        ]
 [-0.33333333  1.          0.        ]
 [-1.33333333  0.          1.        ]] 


primeiro prod: 
 [[ 3.          2.          4.        ]
 [ 0.          0.33333333  0.66666667]
 [ 0.          0.33333333 -3.33333333]] 


[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0. -1.  1.]] 


segundo prod: 
 [[ 3.         -2.          4.        ]
 [ 0.         -0.33333333  0.66666667]
 [ 0.          3.66666667 -3.33333333]] 


[[ 1.00000000e+00  1.66666667e+00 -4.44089210e-16]]
